// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/growthevent"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GrowthEventUpdate is the builder for updating GrowthEvent entities.
type GrowthEventUpdate struct {
	config
	hooks    []Hook
	mutation *GrowthEventMutation
}

// Where appends a list predicates to the GrowthEventUpdate builder.
func (_u *GrowthEventUpdate) Where(ps ...predicate.GrowthEvent) *GrowthEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *GrowthEventUpdate) SetEventType(v string) *GrowthEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *GrowthEventUpdate) SetNillableEventType(v *string) *GrowthEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetCampaignID sets the "campaign_id" field.
func (_u *GrowthEventUpdate) SetCampaignID(v string) *GrowthEventUpdate {
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *GrowthEventUpdate) SetNillableCampaignID(v *string) *GrowthEventUpdate {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *GrowthEventUpdate) SetPlatform(v string) *GrowthEventUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *GrowthEventUpdate) SetNillablePlatform(v *string) *GrowthEventUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetAppVersion sets the "app_version" field.
func (_u *GrowthEventUpdate) SetAppVersion(v string) *GrowthEventUpdate {
	_u.mutation.SetAppVersion(v)
	return _u
}

// SetNillableAppVersion sets the "app_version" field if the given value is not nil.
func (_u *GrowthEventUpdate) SetNillableAppVersion(v *string) *GrowthEventUpdate {
	if v != nil {
		_u.SetAppVersion(*v)
	}
	return _u
}

// SetSessionHash sets the "session_hash" field.
func (_u *GrowthEventUpdate) SetSessionHash(v string) *GrowthEventUpdate {
	_u.mutation.SetSessionHash(v)
	return _u
}

// SetNillableSessionHash sets the "session_hash" field if the given value is not nil.
func (_u *GrowthEventUpdate) SetNillableSessionHash(v *string) *GrowthEventUpdate {
	if v != nil {
		_u.SetSessionHash(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GrowthEventUpdate) SetUserID(v int64) *GrowthEventUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GrowthEventUpdate) SetNillableUserID(v *int64) *GrowthEventUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *GrowthEventUpdate) AddUserID(v int64) *GrowthEventUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *GrowthEventUpdate) ClearUserID() *GrowthEventUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *GrowthEventUpdate) SetPlanID(v int64) *GrowthEventUpdate {
	_u.mutation.ResetPlanID()
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *GrowthEventUpdate) SetNillablePlanID(v *int64) *GrowthEventUpdate {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// AddPlanID adds value to the "plan_id" field.
func (_u *GrowthEventUpdate) AddPlanID(v int64) *GrowthEventUpdate {
	_u.mutation.AddPlanID(v)
	return _u
}

// ClearPlanID clears the value of the "plan_id" field.
func (_u *GrowthEventUpdate) ClearPlanID() *GrowthEventUpdate {
	_u.mutation.ClearPlanID()
	return _u
}

// SetPaymentProvider sets the "payment_provider" field.
func (_u *GrowthEventUpdate) SetPaymentProvider(v string) *GrowthEventUpdate {
	_u.mutation.SetPaymentProvider(v)
	return _u
}

// SetNillablePaymentProvider sets the "payment_provider" field if the given value is not nil.
func (_u *GrowthEventUpdate) SetNillablePaymentProvider(v *string) *GrowthEventUpdate {
	if v != nil {
		_u.SetPaymentProvider(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *GrowthEventUpdate) SetResult(v string) *GrowthEventUpdate {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *GrowthEventUpdate) SetNillableResult(v *string) *GrowthEventUpdate {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *GrowthEventUpdate) SetErrorCode(v string) *GrowthEventUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *GrowthEventUpdate) SetNillableErrorCode(v *string) *GrowthEventUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// Mutation returns the GrowthEventMutation object of the builder.
func (_u *GrowthEventUpdate) Mutation() *GrowthEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GrowthEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GrowthEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GrowthEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GrowthEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GrowthEventUpdate) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := growthevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CampaignID(); ok {
		if err := growthevent.CampaignIDValidator(v); err != nil {
			return &ValidationError{Name: "campaign_id", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.campaign_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := growthevent.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppVersion(); ok {
		if err := growthevent.AppVersionValidator(v); err != nil {
			return &ValidationError{Name: "app_version", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.app_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionHash(); ok {
		if err := growthevent.SessionHashValidator(v); err != nil {
			return &ValidationError{Name: "session_hash", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.session_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentProvider(); ok {
		if err := growthevent.PaymentProviderValidator(v); err != nil {
			return &ValidationError{Name: "payment_provider", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.payment_provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Result(); ok {
		if err := growthevent.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.result": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := growthevent.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *GrowthEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(growthevent.Table, growthevent.Columns, sqlgraph.NewFieldSpec(growthevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(growthevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CampaignID(); ok {
		_spec.SetField(growthevent.FieldCampaignID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(growthevent.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppVersion(); ok {
		_spec.SetField(growthevent.FieldAppVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionHash(); ok {
		_spec.SetField(growthevent.FieldSessionHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(growthevent.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(growthevent.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(growthevent.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.PlanID(); ok {
		_spec.SetField(growthevent.FieldPlanID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlanID(); ok {
		_spec.AddField(growthevent.FieldPlanID, field.TypeInt64, value)
	}
	if _u.mutation.PlanIDCleared() {
		_spec.ClearField(growthevent.FieldPlanID, field.TypeInt64)
	}
	if value, ok := _u.mutation.PaymentProvider(); ok {
		_spec.SetField(growthevent.FieldPaymentProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(growthevent.FieldResult, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(growthevent.FieldErrorCode, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{growthevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GrowthEventUpdateOne is the builder for updating a single GrowthEvent entity.
type GrowthEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GrowthEventMutation
}

// SetEventType sets the "event_type" field.
func (_u *GrowthEventUpdateOne) SetEventType(v string) *GrowthEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *GrowthEventUpdateOne) SetNillableEventType(v *string) *GrowthEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetCampaignID sets the "campaign_id" field.
func (_u *GrowthEventUpdateOne) SetCampaignID(v string) *GrowthEventUpdateOne {
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *GrowthEventUpdateOne) SetNillableCampaignID(v *string) *GrowthEventUpdateOne {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *GrowthEventUpdateOne) SetPlatform(v string) *GrowthEventUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *GrowthEventUpdateOne) SetNillablePlatform(v *string) *GrowthEventUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetAppVersion sets the "app_version" field.
func (_u *GrowthEventUpdateOne) SetAppVersion(v string) *GrowthEventUpdateOne {
	_u.mutation.SetAppVersion(v)
	return _u
}

// SetNillableAppVersion sets the "app_version" field if the given value is not nil.
func (_u *GrowthEventUpdateOne) SetNillableAppVersion(v *string) *GrowthEventUpdateOne {
	if v != nil {
		_u.SetAppVersion(*v)
	}
	return _u
}

// SetSessionHash sets the "session_hash" field.
func (_u *GrowthEventUpdateOne) SetSessionHash(v string) *GrowthEventUpdateOne {
	_u.mutation.SetSessionHash(v)
	return _u
}

// SetNillableSessionHash sets the "session_hash" field if the given value is not nil.
func (_u *GrowthEventUpdateOne) SetNillableSessionHash(v *string) *GrowthEventUpdateOne {
	if v != nil {
		_u.SetSessionHash(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GrowthEventUpdateOne) SetUserID(v int64) *GrowthEventUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GrowthEventUpdateOne) SetNillableUserID(v *int64) *GrowthEventUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *GrowthEventUpdateOne) AddUserID(v int64) *GrowthEventUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *GrowthEventUpdateOne) ClearUserID() *GrowthEventUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *GrowthEventUpdateOne) SetPlanID(v int64) *GrowthEventUpdateOne {
	_u.mutation.ResetPlanID()
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *GrowthEventUpdateOne) SetNillablePlanID(v *int64) *GrowthEventUpdateOne {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// AddPlanID adds value to the "plan_id" field.
func (_u *GrowthEventUpdateOne) AddPlanID(v int64) *GrowthEventUpdateOne {
	_u.mutation.AddPlanID(v)
	return _u
}

// ClearPlanID clears the value of the "plan_id" field.
func (_u *GrowthEventUpdateOne) ClearPlanID() *GrowthEventUpdateOne {
	_u.mutation.ClearPlanID()
	return _u
}

// SetPaymentProvider sets the "payment_provider" field.
func (_u *GrowthEventUpdateOne) SetPaymentProvider(v string) *GrowthEventUpdateOne {
	_u.mutation.SetPaymentProvider(v)
	return _u
}

// SetNillablePaymentProvider sets the "payment_provider" field if the given value is not nil.
func (_u *GrowthEventUpdateOne) SetNillablePaymentProvider(v *string) *GrowthEventUpdateOne {
	if v != nil {
		_u.SetPaymentProvider(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *GrowthEventUpdateOne) SetResult(v string) *GrowthEventUpdateOne {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *GrowthEventUpdateOne) SetNillableResult(v *string) *GrowthEventUpdateOne {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *GrowthEventUpdateOne) SetErrorCode(v string) *GrowthEventUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *GrowthEventUpdateOne) SetNillableErrorCode(v *string) *GrowthEventUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// Mutation returns the GrowthEventMutation object of the builder.
func (_u *GrowthEventUpdateOne) Mutation() *GrowthEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the GrowthEventUpdate builder.
func (_u *GrowthEventUpdateOne) Where(ps ...predicate.GrowthEvent) *GrowthEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GrowthEventUpdateOne) Select(field string, fields ...string) *GrowthEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GrowthEvent entity.
func (_u *GrowthEventUpdateOne) Save(ctx context.Context) (*GrowthEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GrowthEventUpdateOne) SaveX(ctx context.Context) *GrowthEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GrowthEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GrowthEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GrowthEventUpdateOne) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := growthevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CampaignID(); ok {
		if err := growthevent.CampaignIDValidator(v); err != nil {
			return &ValidationError{Name: "campaign_id", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.campaign_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := growthevent.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppVersion(); ok {
		if err := growthevent.AppVersionValidator(v); err != nil {
			return &ValidationError{Name: "app_version", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.app_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionHash(); ok {
		if err := growthevent.SessionHashValidator(v); err != nil {
			return &ValidationError{Name: "session_hash", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.session_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentProvider(); ok {
		if err := growthevent.PaymentProviderValidator(v); err != nil {
			return &ValidationError{Name: "payment_provider", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.payment_provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Result(); ok {
		if err := growthevent.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.result": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := growthevent.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *GrowthEventUpdateOne) sqlSave(ctx context.Context) (_node *GrowthEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(growthevent.Table, growthevent.Columns, sqlgraph.NewFieldSpec(growthevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GrowthEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, growthevent.FieldID)
		for _, f := range fields {
			if !growthevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != growthevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(growthevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CampaignID(); ok {
		_spec.SetField(growthevent.FieldCampaignID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(growthevent.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppVersion(); ok {
		_spec.SetField(growthevent.FieldAppVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionHash(); ok {
		_spec.SetField(growthevent.FieldSessionHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(growthevent.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(growthevent.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(growthevent.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.PlanID(); ok {
		_spec.SetField(growthevent.FieldPlanID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlanID(); ok {
		_spec.AddField(growthevent.FieldPlanID, field.TypeInt64, value)
	}
	if _u.mutation.PlanIDCleared() {
		_spec.ClearField(growthevent.FieldPlanID, field.TypeInt64)
	}
	if value, ok := _u.mutation.PaymentProvider(); ok {
		_spec.SetField(growthevent.FieldPaymentProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(growthevent.FieldResult, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(growthevent.FieldErrorCode, field.TypeString, value)
	}
	_node = &GrowthEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{growthevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
