// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/growthevent"
)

// GrowthEvent is the model entity for the GrowthEvent schema.
type GrowthEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// CampaignID holds the value of the "campaign_id" field.
	CampaignID string `json:"campaign_id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// AppVersion holds the value of the "app_version" field.
	AppVersion string `json:"app_version,omitempty"`
	// SessionHash holds the value of the "session_hash" field.
	SessionHash string `json:"session_hash,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *int64 `json:"user_id,omitempty"`
	// PlanID holds the value of the "plan_id" field.
	PlanID *int64 `json:"plan_id,omitempty"`
	// PaymentProvider holds the value of the "payment_provider" field.
	PaymentProvider string `json:"payment_provider,omitempty"`
	// Result holds the value of the "result" field.
	Result string `json:"result,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode string `json:"error_code,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GrowthEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case growthevent.FieldID, growthevent.FieldUserID, growthevent.FieldPlanID:
			values[i] = new(sql.NullInt64)
		case growthevent.FieldEventType, growthevent.FieldCampaignID, growthevent.FieldPlatform, growthevent.FieldAppVersion, growthevent.FieldSessionHash, growthevent.FieldPaymentProvider, growthevent.FieldResult, growthevent.FieldErrorCode:
			values[i] = new(sql.NullString)
		case growthevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GrowthEvent fields.
func (_m *GrowthEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case growthevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case growthevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case growthevent.FieldCampaignID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field campaign_id", values[i])
			} else if value.Valid {
				_m.CampaignID = value.String
			}
		case growthevent.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case growthevent.FieldAppVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field app_version", values[i])
			} else if value.Valid {
				_m.AppVersion = value.String
			}
		case growthevent.FieldSessionHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_hash", values[i])
			} else if value.Valid {
				_m.SessionHash = value.String
			}
		case growthevent.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(int64)
				*_m.UserID = value.Int64
			}
		case growthevent.FieldPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value.Valid {
				_m.PlanID = new(int64)
				*_m.PlanID = value.Int64
			}
		case growthevent.FieldPaymentProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_provider", values[i])
			} else if value.Valid {
				_m.PaymentProvider = value.String
			}
		case growthevent.FieldResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result", values[i])
			} else if value.Valid {
				_m.Result = value.String
			}
		case growthevent.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = value.String
			}
		case growthevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GrowthEvent.
// This includes values selected through modifiers, order, etc.
func (_m *GrowthEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GrowthEvent.
// Note that you need to call GrowthEvent.Unwrap() before calling this method if this GrowthEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GrowthEvent) Update() *GrowthEventUpdateOne {
	return NewGrowthEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GrowthEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GrowthEvent) Unwrap() *GrowthEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GrowthEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GrowthEvent) String() string {
	var builder strings.Builder
	builder.WriteString("GrowthEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("campaign_id=")
	builder.WriteString(_m.CampaignID)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("app_version=")
	builder.WriteString(_m.AppVersion)
	builder.WriteString(", ")
	builder.WriteString("session_hash=")
	builder.WriteString(_m.SessionHash)
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PlanID; v != nil {
		builder.WriteString("plan_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("payment_provider=")
	builder.WriteString(_m.PaymentProvider)
	builder.WriteString(", ")
	builder.WriteString("result=")
	builder.WriteString(_m.Result)
	builder.WriteString(", ")
	builder.WriteString("error_code=")
	builder.WriteString(_m.ErrorCode)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GrowthEvents is a parsable slice of GrowthEvent.
type GrowthEvents []*GrowthEvent
