// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/growthevent"
)

// GrowthEventCreate is the builder for creating a GrowthEvent entity.
type GrowthEventCreate struct {
	config
	mutation *GrowthEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEventType sets the "event_type" field.
func (_c *GrowthEventCreate) SetEventType(v string) *GrowthEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetCampaignID sets the "campaign_id" field.
func (_c *GrowthEventCreate) SetCampaignID(v string) *GrowthEventCreate {
	_c.mutation.SetCampaignID(v)
	return _c
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_c *GrowthEventCreate) SetNillableCampaignID(v *string) *GrowthEventCreate {
	if v != nil {
		_c.SetCampaignID(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *GrowthEventCreate) SetPlatform(v string) *GrowthEventCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *GrowthEventCreate) SetNillablePlatform(v *string) *GrowthEventCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetAppVersion sets the "app_version" field.
func (_c *GrowthEventCreate) SetAppVersion(v string) *GrowthEventCreate {
	_c.mutation.SetAppVersion(v)
	return _c
}

// SetNillableAppVersion sets the "app_version" field if the given value is not nil.
func (_c *GrowthEventCreate) SetNillableAppVersion(v *string) *GrowthEventCreate {
	if v != nil {
		_c.SetAppVersion(*v)
	}
	return _c
}

// SetSessionHash sets the "session_hash" field.
func (_c *GrowthEventCreate) SetSessionHash(v string) *GrowthEventCreate {
	_c.mutation.SetSessionHash(v)
	return _c
}

// SetNillableSessionHash sets the "session_hash" field if the given value is not nil.
func (_c *GrowthEventCreate) SetNillableSessionHash(v *string) *GrowthEventCreate {
	if v != nil {
		_c.SetSessionHash(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *GrowthEventCreate) SetUserID(v int64) *GrowthEventCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *GrowthEventCreate) SetNillableUserID(v *int64) *GrowthEventCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *GrowthEventCreate) SetPlanID(v int64) *GrowthEventCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_c *GrowthEventCreate) SetNillablePlanID(v *int64) *GrowthEventCreate {
	if v != nil {
		_c.SetPlanID(*v)
	}
	return _c
}

// SetPaymentProvider sets the "payment_provider" field.
func (_c *GrowthEventCreate) SetPaymentProvider(v string) *GrowthEventCreate {
	_c.mutation.SetPaymentProvider(v)
	return _c
}

// SetNillablePaymentProvider sets the "payment_provider" field if the given value is not nil.
func (_c *GrowthEventCreate) SetNillablePaymentProvider(v *string) *GrowthEventCreate {
	if v != nil {
		_c.SetPaymentProvider(*v)
	}
	return _c
}

// SetResult sets the "result" field.
func (_c *GrowthEventCreate) SetResult(v string) *GrowthEventCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_c *GrowthEventCreate) SetNillableResult(v *string) *GrowthEventCreate {
	if v != nil {
		_c.SetResult(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *GrowthEventCreate) SetErrorCode(v string) *GrowthEventCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *GrowthEventCreate) SetNillableErrorCode(v *string) *GrowthEventCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GrowthEventCreate) SetCreatedAt(v time.Time) *GrowthEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GrowthEventCreate) SetNillableCreatedAt(v *time.Time) *GrowthEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the GrowthEventMutation object of the builder.
func (_c *GrowthEventCreate) Mutation() *GrowthEventMutation {
	return _c.mutation
}

// Save creates the GrowthEvent in the database.
func (_c *GrowthEventCreate) Save(ctx context.Context) (*GrowthEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GrowthEventCreate) SaveX(ctx context.Context) *GrowthEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GrowthEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GrowthEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GrowthEventCreate) defaults() {
	if _, ok := _c.mutation.CampaignID(); !ok {
		v := growthevent.DefaultCampaignID
		_c.mutation.SetCampaignID(v)
	}
	if _, ok := _c.mutation.Platform(); !ok {
		v := growthevent.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.AppVersion(); !ok {
		v := growthevent.DefaultAppVersion
		_c.mutation.SetAppVersion(v)
	}
	if _, ok := _c.mutation.SessionHash(); !ok {
		v := growthevent.DefaultSessionHash
		_c.mutation.SetSessionHash(v)
	}
	if _, ok := _c.mutation.PaymentProvider(); !ok {
		v := growthevent.DefaultPaymentProvider
		_c.mutation.SetPaymentProvider(v)
	}
	if _, ok := _c.mutation.Result(); !ok {
		v := growthevent.DefaultResult
		_c.mutation.SetResult(v)
	}
	if _, ok := _c.mutation.ErrorCode(); !ok {
		v := growthevent.DefaultErrorCode
		_c.mutation.SetErrorCode(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := growthevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GrowthEventCreate) check() error {
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "GrowthEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := growthevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CampaignID(); !ok {
		return &ValidationError{Name: "campaign_id", err: errors.New(`ent: missing required field "GrowthEvent.campaign_id"`)}
	}
	if v, ok := _c.mutation.CampaignID(); ok {
		if err := growthevent.CampaignIDValidator(v); err != nil {
			return &ValidationError{Name: "campaign_id", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.campaign_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "GrowthEvent.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := growthevent.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AppVersion(); !ok {
		return &ValidationError{Name: "app_version", err: errors.New(`ent: missing required field "GrowthEvent.app_version"`)}
	}
	if v, ok := _c.mutation.AppVersion(); ok {
		if err := growthevent.AppVersionValidator(v); err != nil {
			return &ValidationError{Name: "app_version", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.app_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SessionHash(); !ok {
		return &ValidationError{Name: "session_hash", err: errors.New(`ent: missing required field "GrowthEvent.session_hash"`)}
	}
	if v, ok := _c.mutation.SessionHash(); ok {
		if err := growthevent.SessionHashValidator(v); err != nil {
			return &ValidationError{Name: "session_hash", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.session_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaymentProvider(); !ok {
		return &ValidationError{Name: "payment_provider", err: errors.New(`ent: missing required field "GrowthEvent.payment_provider"`)}
	}
	if v, ok := _c.mutation.PaymentProvider(); ok {
		if err := growthevent.PaymentProviderValidator(v); err != nil {
			return &ValidationError{Name: "payment_provider", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.payment_provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Result(); !ok {
		return &ValidationError{Name: "result", err: errors.New(`ent: missing required field "GrowthEvent.result"`)}
	}
	if v, ok := _c.mutation.Result(); ok {
		if err := growthevent.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.result": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ErrorCode(); !ok {
		return &ValidationError{Name: "error_code", err: errors.New(`ent: missing required field "GrowthEvent.error_code"`)}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := growthevent.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "GrowthEvent.error_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GrowthEvent.created_at"`)}
	}
	return nil
}

func (_c *GrowthEventCreate) sqlSave(ctx context.Context) (*GrowthEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GrowthEventCreate) createSpec() (*GrowthEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &GrowthEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(growthevent.Table, sqlgraph.NewFieldSpec(growthevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(growthevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.CampaignID(); ok {
		_spec.SetField(growthevent.FieldCampaignID, field.TypeString, value)
		_node.CampaignID = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(growthevent.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.AppVersion(); ok {
		_spec.SetField(growthevent.FieldAppVersion, field.TypeString, value)
		_node.AppVersion = value
	}
	if value, ok := _c.mutation.SessionHash(); ok {
		_spec.SetField(growthevent.FieldSessionHash, field.TypeString, value)
		_node.SessionHash = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(growthevent.FieldUserID, field.TypeInt64, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.PlanID(); ok {
		_spec.SetField(growthevent.FieldPlanID, field.TypeInt64, value)
		_node.PlanID = &value
	}
	if value, ok := _c.mutation.PaymentProvider(); ok {
		_spec.SetField(growthevent.FieldPaymentProvider, field.TypeString, value)
		_node.PaymentProvider = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(growthevent.FieldResult, field.TypeString, value)
		_node.Result = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(growthevent.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(growthevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GrowthEvent.Create().
//		SetEventType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GrowthEventUpsert) {
//			SetEventType(v+v).
//		}).
//		Exec(ctx)
func (_c *GrowthEventCreate) OnConflict(opts ...sql.ConflictOption) *GrowthEventUpsertOne {
	_c.conflict = opts
	return &GrowthEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GrowthEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GrowthEventCreate) OnConflictColumns(columns ...string) *GrowthEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GrowthEventUpsertOne{
		create: _c,
	}
}

type (
	// GrowthEventUpsertOne is the builder for "upsert"-ing
	//  one GrowthEvent node.
	GrowthEventUpsertOne struct {
		create *GrowthEventCreate
	}

	// GrowthEventUpsert is the "OnConflict" setter.
	GrowthEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetEventType sets the "event_type" field.
func (u *GrowthEventUpsert) SetEventType(v string) *GrowthEventUpsert {
	u.Set(growthevent.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *GrowthEventUpsert) UpdateEventType() *GrowthEventUpsert {
	u.SetExcluded(growthevent.FieldEventType)
	return u
}

// SetCampaignID sets the "campaign_id" field.
func (u *GrowthEventUpsert) SetCampaignID(v string) *GrowthEventUpsert {
	u.Set(growthevent.FieldCampaignID, v)
	return u
}

// UpdateCampaignID sets the "campaign_id" field to the value that was provided on create.
func (u *GrowthEventUpsert) UpdateCampaignID() *GrowthEventUpsert {
	u.SetExcluded(growthevent.FieldCampaignID)
	return u
}

// SetPlatform sets the "platform" field.
func (u *GrowthEventUpsert) SetPlatform(v string) *GrowthEventUpsert {
	u.Set(growthevent.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *GrowthEventUpsert) UpdatePlatform() *GrowthEventUpsert {
	u.SetExcluded(growthevent.FieldPlatform)
	return u
}

// SetAppVersion sets the "app_version" field.
func (u *GrowthEventUpsert) SetAppVersion(v string) *GrowthEventUpsert {
	u.Set(growthevent.FieldAppVersion, v)
	return u
}

// UpdateAppVersion sets the "app_version" field to the value that was provided on create.
func (u *GrowthEventUpsert) UpdateAppVersion() *GrowthEventUpsert {
	u.SetExcluded(growthevent.FieldAppVersion)
	return u
}

// SetSessionHash sets the "session_hash" field.
func (u *GrowthEventUpsert) SetSessionHash(v string) *GrowthEventUpsert {
	u.Set(growthevent.FieldSessionHash, v)
	return u
}

// UpdateSessionHash sets the "session_hash" field to the value that was provided on create.
func (u *GrowthEventUpsert) UpdateSessionHash() *GrowthEventUpsert {
	u.SetExcluded(growthevent.FieldSessionHash)
	return u
}

// SetUserID sets the "user_id" field.
func (u *GrowthEventUpsert) SetUserID(v int64) *GrowthEventUpsert {
	u.Set(growthevent.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *GrowthEventUpsert) UpdateUserID() *GrowthEventUpsert {
	u.SetExcluded(growthevent.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *GrowthEventUpsert) AddUserID(v int64) *GrowthEventUpsert {
	u.Add(growthevent.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *GrowthEventUpsert) ClearUserID() *GrowthEventUpsert {
	u.SetNull(growthevent.FieldUserID)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *GrowthEventUpsert) SetPlanID(v int64) *GrowthEventUpsert {
	u.Set(growthevent.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *GrowthEventUpsert) UpdatePlanID() *GrowthEventUpsert {
	u.SetExcluded(growthevent.FieldPlanID)
	return u
}

// AddPlanID adds v to the "plan_id" field.
func (u *GrowthEventUpsert) AddPlanID(v int64) *GrowthEventUpsert {
	u.Add(growthevent.FieldPlanID, v)
	return u
}

// ClearPlanID clears the value of the "plan_id" field.
func (u *GrowthEventUpsert) ClearPlanID() *GrowthEventUpsert {
	u.SetNull(growthevent.FieldPlanID)
	return u
}

// SetPaymentProvider sets the "payment_provider" field.
func (u *GrowthEventUpsert) SetPaymentProvider(v string) *GrowthEventUpsert {
	u.Set(growthevent.FieldPaymentProvider, v)
	return u
}

// UpdatePaymentProvider sets the "payment_provider" field to the value that was provided on create.
func (u *GrowthEventUpsert) UpdatePaymentProvider() *GrowthEventUpsert {
	u.SetExcluded(growthevent.FieldPaymentProvider)
	return u
}

// SetResult sets the "result" field.
func (u *GrowthEventUpsert) SetResult(v string) *GrowthEventUpsert {
	u.Set(growthevent.FieldResult, v)
	return u
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *GrowthEventUpsert) UpdateResult() *GrowthEventUpsert {
	u.SetExcluded(growthevent.FieldResult)
	return u
}

// SetErrorCode sets the "error_code" field.
func (u *GrowthEventUpsert) SetErrorCode(v string) *GrowthEventUpsert {
	u.Set(growthevent.FieldErrorCode, v)
	return u
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *GrowthEventUpsert) UpdateErrorCode() *GrowthEventUpsert {
	u.SetExcluded(growthevent.FieldErrorCode)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GrowthEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GrowthEventUpsertOne) UpdateNewValues() *GrowthEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(growthevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GrowthEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GrowthEventUpsertOne) Ignore() *GrowthEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GrowthEventUpsertOne) DoNothing() *GrowthEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GrowthEventCreate.OnConflict
// documentation for more info.
func (u *GrowthEventUpsertOne) Update(set func(*GrowthEventUpsert)) *GrowthEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GrowthEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetEventType sets the "event_type" field.
func (u *GrowthEventUpsertOne) SetEventType(v string) *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *GrowthEventUpsertOne) UpdateEventType() *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdateEventType()
	})
}

// SetCampaignID sets the "campaign_id" field.
func (u *GrowthEventUpsertOne) SetCampaignID(v string) *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetCampaignID(v)
	})
}

// UpdateCampaignID sets the "campaign_id" field to the value that was provided on create.
func (u *GrowthEventUpsertOne) UpdateCampaignID() *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdateCampaignID()
	})
}

// SetPlatform sets the "platform" field.
func (u *GrowthEventUpsertOne) SetPlatform(v string) *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *GrowthEventUpsertOne) UpdatePlatform() *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdatePlatform()
	})
}

// SetAppVersion sets the "app_version" field.
func (u *GrowthEventUpsertOne) SetAppVersion(v string) *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetAppVersion(v)
	})
}

// UpdateAppVersion sets the "app_version" field to the value that was provided on create.
func (u *GrowthEventUpsertOne) UpdateAppVersion() *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdateAppVersion()
	})
}

// SetSessionHash sets the "session_hash" field.
func (u *GrowthEventUpsertOne) SetSessionHash(v string) *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetSessionHash(v)
	})
}

// UpdateSessionHash sets the "session_hash" field to the value that was provided on create.
func (u *GrowthEventUpsertOne) UpdateSessionHash() *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdateSessionHash()
	})
}

// SetUserID sets the "user_id" field.
func (u *GrowthEventUpsertOne) SetUserID(v int64) *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *GrowthEventUpsertOne) AddUserID(v int64) *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *GrowthEventUpsertOne) UpdateUserID() *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *GrowthEventUpsertOne) ClearUserID() *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.ClearUserID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *GrowthEventUpsertOne) SetPlanID(v int64) *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *GrowthEventUpsertOne) AddPlanID(v int64) *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *GrowthEventUpsertOne) UpdatePlanID() *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdatePlanID()
	})
}

// ClearPlanID clears the value of the "plan_id" field.
func (u *GrowthEventUpsertOne) ClearPlanID() *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.ClearPlanID()
	})
}

// SetPaymentProvider sets the "payment_provider" field.
func (u *GrowthEventUpsertOne) SetPaymentProvider(v string) *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetPaymentProvider(v)
	})
}

// UpdatePaymentProvider sets the "payment_provider" field to the value that was provided on create.
func (u *GrowthEventUpsertOne) UpdatePaymentProvider() *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdatePaymentProvider()
	})
}

// SetResult sets the "result" field.
func (u *GrowthEventUpsertOne) SetResult(v string) *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *GrowthEventUpsertOne) UpdateResult() *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdateResult()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *GrowthEventUpsertOne) SetErrorCode(v string) *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *GrowthEventUpsertOne) UpdateErrorCode() *GrowthEventUpsertOne {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdateErrorCode()
	})
}

// Exec executes the query.
func (u *GrowthEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GrowthEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GrowthEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GrowthEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GrowthEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GrowthEventCreateBulk is the builder for creating many GrowthEvent entities in bulk.
type GrowthEventCreateBulk struct {
	config
	err      error
	builders []*GrowthEventCreate
	conflict []sql.ConflictOption
}

// Save creates the GrowthEvent entities in the database.
func (_c *GrowthEventCreateBulk) Save(ctx context.Context) ([]*GrowthEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GrowthEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GrowthEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GrowthEventCreateBulk) SaveX(ctx context.Context) []*GrowthEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GrowthEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GrowthEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GrowthEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GrowthEventUpsert) {
//			SetEventType(v+v).
//		}).
//		Exec(ctx)
func (_c *GrowthEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *GrowthEventUpsertBulk {
	_c.conflict = opts
	return &GrowthEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GrowthEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GrowthEventCreateBulk) OnConflictColumns(columns ...string) *GrowthEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GrowthEventUpsertBulk{
		create: _c,
	}
}

// GrowthEventUpsertBulk is the builder for "upsert"-ing
// a bulk of GrowthEvent nodes.
type GrowthEventUpsertBulk struct {
	create *GrowthEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GrowthEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GrowthEventUpsertBulk) UpdateNewValues() *GrowthEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(growthevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GrowthEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GrowthEventUpsertBulk) Ignore() *GrowthEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GrowthEventUpsertBulk) DoNothing() *GrowthEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GrowthEventCreateBulk.OnConflict
// documentation for more info.
func (u *GrowthEventUpsertBulk) Update(set func(*GrowthEventUpsert)) *GrowthEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GrowthEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetEventType sets the "event_type" field.
func (u *GrowthEventUpsertBulk) SetEventType(v string) *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *GrowthEventUpsertBulk) UpdateEventType() *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdateEventType()
	})
}

// SetCampaignID sets the "campaign_id" field.
func (u *GrowthEventUpsertBulk) SetCampaignID(v string) *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetCampaignID(v)
	})
}

// UpdateCampaignID sets the "campaign_id" field to the value that was provided on create.
func (u *GrowthEventUpsertBulk) UpdateCampaignID() *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdateCampaignID()
	})
}

// SetPlatform sets the "platform" field.
func (u *GrowthEventUpsertBulk) SetPlatform(v string) *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *GrowthEventUpsertBulk) UpdatePlatform() *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdatePlatform()
	})
}

// SetAppVersion sets the "app_version" field.
func (u *GrowthEventUpsertBulk) SetAppVersion(v string) *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetAppVersion(v)
	})
}

// UpdateAppVersion sets the "app_version" field to the value that was provided on create.
func (u *GrowthEventUpsertBulk) UpdateAppVersion() *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdateAppVersion()
	})
}

// SetSessionHash sets the "session_hash" field.
func (u *GrowthEventUpsertBulk) SetSessionHash(v string) *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetSessionHash(v)
	})
}

// UpdateSessionHash sets the "session_hash" field to the value that was provided on create.
func (u *GrowthEventUpsertBulk) UpdateSessionHash() *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdateSessionHash()
	})
}

// SetUserID sets the "user_id" field.
func (u *GrowthEventUpsertBulk) SetUserID(v int64) *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *GrowthEventUpsertBulk) AddUserID(v int64) *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *GrowthEventUpsertBulk) UpdateUserID() *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *GrowthEventUpsertBulk) ClearUserID() *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.ClearUserID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *GrowthEventUpsertBulk) SetPlanID(v int64) *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *GrowthEventUpsertBulk) AddPlanID(v int64) *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *GrowthEventUpsertBulk) UpdatePlanID() *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdatePlanID()
	})
}

// ClearPlanID clears the value of the "plan_id" field.
func (u *GrowthEventUpsertBulk) ClearPlanID() *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.ClearPlanID()
	})
}

// SetPaymentProvider sets the "payment_provider" field.
func (u *GrowthEventUpsertBulk) SetPaymentProvider(v string) *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetPaymentProvider(v)
	})
}

// UpdatePaymentProvider sets the "payment_provider" field to the value that was provided on create.
func (u *GrowthEventUpsertBulk) UpdatePaymentProvider() *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdatePaymentProvider()
	})
}

// SetResult sets the "result" field.
func (u *GrowthEventUpsertBulk) SetResult(v string) *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *GrowthEventUpsertBulk) UpdateResult() *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdateResult()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *GrowthEventUpsertBulk) SetErrorCode(v string) *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *GrowthEventUpsertBulk) UpdateErrorCode() *GrowthEventUpsertBulk {
	return u.Update(func(s *GrowthEventUpsert) {
		s.UpdateErrorCode()
	})
}

// Exec executes the query.
func (u *GrowthEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GrowthEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GrowthEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GrowthEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
