// Code generated by ent, DO NOT EDIT.

package growthevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the growthevent type in the database.
	Label = "growth_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldCampaignID holds the string denoting the campaign_id field in the database.
	FieldCampaignID = "campaign_id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldAppVersion holds the string denoting the app_version field in the database.
	FieldAppVersion = "app_version"
	// FieldSessionHash holds the string denoting the session_hash field in the database.
	FieldSessionHash = "session_hash"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPlanID holds the string denoting the plan_id field in the database.
	FieldPlanID = "plan_id"
	// FieldPaymentProvider holds the string denoting the payment_provider field in the database.
	FieldPaymentProvider = "payment_provider"
	// FieldResult holds the string denoting the result field in the database.
	FieldResult = "result"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the growthevent in the database.
	Table = "growth_events"
)

// Columns holds all SQL columns for growthevent fields.
var Columns = []string{
	FieldID,
	FieldEventType,
	FieldCampaignID,
	FieldPlatform,
	FieldAppVersion,
	FieldSessionHash,
	FieldUserID,
	FieldPlanID,
	FieldPaymentProvider,
	FieldResult,
	FieldErrorCode,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	EventTypeValidator func(string) error
	// DefaultCampaignID holds the default value on creation for the "campaign_id" field.
	DefaultCampaignID string
	// CampaignIDValidator is a validator for the "campaign_id" field. It is called by the builders before save.
	CampaignIDValidator func(string) error
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultAppVersion holds the default value on creation for the "app_version" field.
	DefaultAppVersion string
	// AppVersionValidator is a validator for the "app_version" field. It is called by the builders before save.
	AppVersionValidator func(string) error
	// DefaultSessionHash holds the default value on creation for the "session_hash" field.
	DefaultSessionHash string
	// SessionHashValidator is a validator for the "session_hash" field. It is called by the builders before save.
	SessionHashValidator func(string) error
	// DefaultPaymentProvider holds the default value on creation for the "payment_provider" field.
	DefaultPaymentProvider string
	// PaymentProviderValidator is a validator for the "payment_provider" field. It is called by the builders before save.
	PaymentProviderValidator func(string) error
	// DefaultResult holds the default value on creation for the "result" field.
	DefaultResult string
	// ResultValidator is a validator for the "result" field. It is called by the builders before save.
	ResultValidator func(string) error
	// DefaultErrorCode holds the default value on creation for the "error_code" field.
	DefaultErrorCode string
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the GrowthEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByCampaignID orders the results by the campaign_id field.
func ByCampaignID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCampaignID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByAppVersion orders the results by the app_version field.
func ByAppVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppVersion, opts...).ToFunc()
}

// BySessionHash orders the results by the session_hash field.
func BySessionHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionHash, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPlanID orders the results by the plan_id field.
func ByPlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanID, opts...).ToFunc()
}

// ByPaymentProvider orders the results by the payment_provider field.
func ByPaymentProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentProvider, opts...).ToFunc()
}

// ByResult orders the results by the result field.
func ByResult(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResult, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
