// Code generated by ent, DO NOT EDIT.

package growthevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLTE(FieldID, id))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldEventType, v))
}

// CampaignID applies equality check predicate on the "campaign_id" field. It's identical to CampaignIDEQ.
func CampaignID(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldCampaignID, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldPlatform, v))
}

// AppVersion applies equality check predicate on the "app_version" field. It's identical to AppVersionEQ.
func AppVersion(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldAppVersion, v))
}

// SessionHash applies equality check predicate on the "session_hash" field. It's identical to SessionHashEQ.
func SessionHash(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldSessionHash, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldUserID, v))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldPlanID, v))
}

// PaymentProvider applies equality check predicate on the "payment_provider" field. It's identical to PaymentProviderEQ.
func PaymentProvider(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldPaymentProvider, v))
}

// Result applies equality check predicate on the "result" field. It's identical to ResultEQ.
func Result(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldResult, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldErrorCode, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldContainsFold(FieldEventType, v))
}

// CampaignIDEQ applies the EQ predicate on the "campaign_id" field.
func CampaignIDEQ(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldCampaignID, v))
}

// CampaignIDNEQ applies the NEQ predicate on the "campaign_id" field.
func CampaignIDNEQ(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNEQ(FieldCampaignID, v))
}

// CampaignIDIn applies the In predicate on the "campaign_id" field.
func CampaignIDIn(vs ...string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldIn(FieldCampaignID, vs...))
}

// CampaignIDNotIn applies the NotIn predicate on the "campaign_id" field.
func CampaignIDNotIn(vs ...string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNotIn(FieldCampaignID, vs...))
}

// CampaignIDGT applies the GT predicate on the "campaign_id" field.
func CampaignIDGT(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGT(FieldCampaignID, v))
}

// CampaignIDGTE applies the GTE predicate on the "campaign_id" field.
func CampaignIDGTE(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGTE(FieldCampaignID, v))
}

// CampaignIDLT applies the LT predicate on the "campaign_id" field.
func CampaignIDLT(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLT(FieldCampaignID, v))
}

// CampaignIDLTE applies the LTE predicate on the "campaign_id" field.
func CampaignIDLTE(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLTE(FieldCampaignID, v))
}

// CampaignIDContains applies the Contains predicate on the "campaign_id" field.
func CampaignIDContains(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldContains(FieldCampaignID, v))
}

// CampaignIDHasPrefix applies the HasPrefix predicate on the "campaign_id" field.
func CampaignIDHasPrefix(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldHasPrefix(FieldCampaignID, v))
}

// CampaignIDHasSuffix applies the HasSuffix predicate on the "campaign_id" field.
func CampaignIDHasSuffix(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldHasSuffix(FieldCampaignID, v))
}

// CampaignIDEqualFold applies the EqualFold predicate on the "campaign_id" field.
func CampaignIDEqualFold(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEqualFold(FieldCampaignID, v))
}

// CampaignIDContainsFold applies the ContainsFold predicate on the "campaign_id" field.
func CampaignIDContainsFold(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldContainsFold(FieldCampaignID, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldContainsFold(FieldPlatform, v))
}

// AppVersionEQ applies the EQ predicate on the "app_version" field.
func AppVersionEQ(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldAppVersion, v))
}

// AppVersionNEQ applies the NEQ predicate on the "app_version" field.
func AppVersionNEQ(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNEQ(FieldAppVersion, v))
}

// AppVersionIn applies the In predicate on the "app_version" field.
func AppVersionIn(vs ...string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldIn(FieldAppVersion, vs...))
}

// AppVersionNotIn applies the NotIn predicate on the "app_version" field.
func AppVersionNotIn(vs ...string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNotIn(FieldAppVersion, vs...))
}

// AppVersionGT applies the GT predicate on the "app_version" field.
func AppVersionGT(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGT(FieldAppVersion, v))
}

// AppVersionGTE applies the GTE predicate on the "app_version" field.
func AppVersionGTE(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGTE(FieldAppVersion, v))
}

// AppVersionLT applies the LT predicate on the "app_version" field.
func AppVersionLT(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLT(FieldAppVersion, v))
}

// AppVersionLTE applies the LTE predicate on the "app_version" field.
func AppVersionLTE(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLTE(FieldAppVersion, v))
}

// AppVersionContains applies the Contains predicate on the "app_version" field.
func AppVersionContains(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldContains(FieldAppVersion, v))
}

// AppVersionHasPrefix applies the HasPrefix predicate on the "app_version" field.
func AppVersionHasPrefix(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldHasPrefix(FieldAppVersion, v))
}

// AppVersionHasSuffix applies the HasSuffix predicate on the "app_version" field.
func AppVersionHasSuffix(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldHasSuffix(FieldAppVersion, v))
}

// AppVersionEqualFold applies the EqualFold predicate on the "app_version" field.
func AppVersionEqualFold(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEqualFold(FieldAppVersion, v))
}

// AppVersionContainsFold applies the ContainsFold predicate on the "app_version" field.
func AppVersionContainsFold(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldContainsFold(FieldAppVersion, v))
}

// SessionHashEQ applies the EQ predicate on the "session_hash" field.
func SessionHashEQ(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldSessionHash, v))
}

// SessionHashNEQ applies the NEQ predicate on the "session_hash" field.
func SessionHashNEQ(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNEQ(FieldSessionHash, v))
}

// SessionHashIn applies the In predicate on the "session_hash" field.
func SessionHashIn(vs ...string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldIn(FieldSessionHash, vs...))
}

// SessionHashNotIn applies the NotIn predicate on the "session_hash" field.
func SessionHashNotIn(vs ...string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNotIn(FieldSessionHash, vs...))
}

// SessionHashGT applies the GT predicate on the "session_hash" field.
func SessionHashGT(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGT(FieldSessionHash, v))
}

// SessionHashGTE applies the GTE predicate on the "session_hash" field.
func SessionHashGTE(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGTE(FieldSessionHash, v))
}

// SessionHashLT applies the LT predicate on the "session_hash" field.
func SessionHashLT(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLT(FieldSessionHash, v))
}

// SessionHashLTE applies the LTE predicate on the "session_hash" field.
func SessionHashLTE(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLTE(FieldSessionHash, v))
}

// SessionHashContains applies the Contains predicate on the "session_hash" field.
func SessionHashContains(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldContains(FieldSessionHash, v))
}

// SessionHashHasPrefix applies the HasPrefix predicate on the "session_hash" field.
func SessionHashHasPrefix(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldHasPrefix(FieldSessionHash, v))
}

// SessionHashHasSuffix applies the HasSuffix predicate on the "session_hash" field.
func SessionHashHasSuffix(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldHasSuffix(FieldSessionHash, v))
}

// SessionHashEqualFold applies the EqualFold predicate on the "session_hash" field.
func SessionHashEqualFold(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEqualFold(FieldSessionHash, v))
}

// SessionHashContainsFold applies the ContainsFold predicate on the "session_hash" field.
func SessionHashContainsFold(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldContainsFold(FieldSessionHash, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNotNull(FieldUserID))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNotIn(FieldPlanID, vs...))
}

// PlanIDGT applies the GT predicate on the "plan_id" field.
func PlanIDGT(v int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGT(FieldPlanID, v))
}

// PlanIDGTE applies the GTE predicate on the "plan_id" field.
func PlanIDGTE(v int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGTE(FieldPlanID, v))
}

// PlanIDLT applies the LT predicate on the "plan_id" field.
func PlanIDLT(v int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLT(FieldPlanID, v))
}

// PlanIDLTE applies the LTE predicate on the "plan_id" field.
func PlanIDLTE(v int64) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLTE(FieldPlanID, v))
}

// PlanIDIsNil applies the IsNil predicate on the "plan_id" field.
func PlanIDIsNil() predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldIsNull(FieldPlanID))
}

// PlanIDNotNil applies the NotNil predicate on the "plan_id" field.
func PlanIDNotNil() predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNotNull(FieldPlanID))
}

// PaymentProviderEQ applies the EQ predicate on the "payment_provider" field.
func PaymentProviderEQ(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldPaymentProvider, v))
}

// PaymentProviderNEQ applies the NEQ predicate on the "payment_provider" field.
func PaymentProviderNEQ(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNEQ(FieldPaymentProvider, v))
}

// PaymentProviderIn applies the In predicate on the "payment_provider" field.
func PaymentProviderIn(vs ...string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldIn(FieldPaymentProvider, vs...))
}

// PaymentProviderNotIn applies the NotIn predicate on the "payment_provider" field.
func PaymentProviderNotIn(vs ...string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNotIn(FieldPaymentProvider, vs...))
}

// PaymentProviderGT applies the GT predicate on the "payment_provider" field.
func PaymentProviderGT(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGT(FieldPaymentProvider, v))
}

// PaymentProviderGTE applies the GTE predicate on the "payment_provider" field.
func PaymentProviderGTE(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGTE(FieldPaymentProvider, v))
}

// PaymentProviderLT applies the LT predicate on the "payment_provider" field.
func PaymentProviderLT(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLT(FieldPaymentProvider, v))
}

// PaymentProviderLTE applies the LTE predicate on the "payment_provider" field.
func PaymentProviderLTE(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLTE(FieldPaymentProvider, v))
}

// PaymentProviderContains applies the Contains predicate on the "payment_provider" field.
func PaymentProviderContains(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldContains(FieldPaymentProvider, v))
}

// PaymentProviderHasPrefix applies the HasPrefix predicate on the "payment_provider" field.
func PaymentProviderHasPrefix(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldHasPrefix(FieldPaymentProvider, v))
}

// PaymentProviderHasSuffix applies the HasSuffix predicate on the "payment_provider" field.
func PaymentProviderHasSuffix(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldHasSuffix(FieldPaymentProvider, v))
}

// PaymentProviderEqualFold applies the EqualFold predicate on the "payment_provider" field.
func PaymentProviderEqualFold(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEqualFold(FieldPaymentProvider, v))
}

// PaymentProviderContainsFold applies the ContainsFold predicate on the "payment_provider" field.
func PaymentProviderContainsFold(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldContainsFold(FieldPaymentProvider, v))
}

// ResultEQ applies the EQ predicate on the "result" field.
func ResultEQ(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldResult, v))
}

// ResultNEQ applies the NEQ predicate on the "result" field.
func ResultNEQ(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNEQ(FieldResult, v))
}

// ResultIn applies the In predicate on the "result" field.
func ResultIn(vs ...string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldIn(FieldResult, vs...))
}

// ResultNotIn applies the NotIn predicate on the "result" field.
func ResultNotIn(vs ...string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNotIn(FieldResult, vs...))
}

// ResultGT applies the GT predicate on the "result" field.
func ResultGT(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGT(FieldResult, v))
}

// ResultGTE applies the GTE predicate on the "result" field.
func ResultGTE(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGTE(FieldResult, v))
}

// ResultLT applies the LT predicate on the "result" field.
func ResultLT(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLT(FieldResult, v))
}

// ResultLTE applies the LTE predicate on the "result" field.
func ResultLTE(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLTE(FieldResult, v))
}

// ResultContains applies the Contains predicate on the "result" field.
func ResultContains(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldContains(FieldResult, v))
}

// ResultHasPrefix applies the HasPrefix predicate on the "result" field.
func ResultHasPrefix(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldHasPrefix(FieldResult, v))
}

// ResultHasSuffix applies the HasSuffix predicate on the "result" field.
func ResultHasSuffix(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldHasSuffix(FieldResult, v))
}

// ResultEqualFold applies the EqualFold predicate on the "result" field.
func ResultEqualFold(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEqualFold(FieldResult, v))
}

// ResultContainsFold applies the ContainsFold predicate on the "result" field.
func ResultContainsFold(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldContainsFold(FieldResult, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldContainsFold(FieldErrorCode, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GrowthEvent) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GrowthEvent) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GrowthEvent) predicate.GrowthEvent {
	return predicate.GrowthEvent(sql.NotPredicates(p))
}
